In [328]:
import numpy as np
import matplotlib.pyplot as plt
import math as m

def voigt(x,amp,x0,gamma,sigma,eta):
    # Función Lorentziana
    L =  (gamma**2 / ((x - x0)**2 + gamma**2))

    # Función Gaussiana
    G =  np.exp(-(x - x0)**2 / (2 * sigma**2)) / (sigma * np.sqrt(2 * np.pi))

    # Perfil de Voigt (combinación de Lorentziana y Gaussiana)
    V=eta * L + (1 - eta) * G
    return amp*np.gradient(V)

In [346]:

x=np.linspace(3000,3600,600)
v=voigt(x,100,3300,10,100,0.5)
v=v/max(v[:])
plt.plot(x,v)
plt.xlabel('Campo magnético $B$ ($G$)', fontsize=22)
plt.ylabel('Intensidad (u.a.)', fontsize=22)
plt.xticks(fontsize=22)
plt.yticks(fontsize=22)
plt.show()

In [283]:
mu=9.27*10**(-21)
h=6.626*10**(-27)
nu=9.526*10**(9)

### Cr+3

In [347]:
I=[3/2,0]
N=[[-3/2,-1/2,1/2,3/2],[0]]
E=[-3/2,-1/2,1/2,3/2]
amp=[2.37525,90.499]

g=1.982967473
A=[g*mu*24.36,0]

In [356]:

x=np.linspace(3395,3472,5000)
espectro_cr=np.zeros(5000)
y=[]

absorciones=[]


for i in range(len(I)):
    for k in range(len(E)):
        for j in range(len(N[i])):

            B1=1/(2*g) * ((h*nu/mu - A[i]*N[i][j]/mu) + ((A[i]*N[i][j]/mu - h*nu/mu)**2 - 2*A[i]**2/(mu**2) * (I[i]*(I[i]+1)+N[i][j]*(-N[i][j]+2*E[k]+1)))**(1/2))
            B2=1/(2*g) * ((h*nu/mu + A[i]*N[i][j]/mu) + ((A[i]*N[i][j]/mu + h*nu/mu)**2 - 2*A[i]**2/(mu**2) * (I[i]*(I[i]+1)+N[i][j]*(-N[i][j]+2*E[k]-1)))**(1/2))

            y.append(voigt(x,amp[i],B1,0.5,0.5,0.5))
            y.append(voigt(x,amp[i],B2,0.5,0.5,0.5))
            absorciones.append(B1)
            absorciones.append(B2)
for i in range(len(y)):
    espectro_cr+=y[i]

espectro_cr=espectro_cr/max(espectro_cr)
plt.xlabel('Campo magnético $B$ ($G$)', fontsize=22)
plt.ylabel('Intensidad (u.a.)', fontsize=22)
plt.xlim(3395,3472)
plt.xticks(fontsize=22)
plt.yticks(fontsize=22)
plt.plot(x,espectro_cr, color='black')



In [359]:
fig, axs = plt.subplots(1)

axs.plot(x,espectro_cr,color='black')


for i in range(len(absorciones)):
    axs.axvline(x=absorciones[i], color='gray', linestyle='--', linewidth=1)

plt.xlabel('Campo magnético $B$ ($G$)', fontsize=22)
plt.ylabel('Intensidad (u.a.)', fontsize=22)
plt.xlim(3395,3472)

plt.xticks(fontsize=22)
plt.yticks(fontsize=22)


(array([-1.25, -1.  , -0.75, -0.5 , -0.25,  0.  ,  0.25,  0.5 ,  0.75,
         1.  ,  1.25]),
 [Text(0, -1.25, '−1.25'),
  Text(0, -1.0, '−1.00'),
  Text(0, -0.75, '−0.75'),
  Text(0, -0.5, '−0.50'),
  Text(0, -0.25, '−0.25'),
  Text(0, 0.0, '0.00'),
  Text(0, 0.25, '0.25'),
  Text(0, 0.5, '0.50'),
  Text(0, 0.75, '0.75'),
  Text(0, 1.0, '1.00'),
  Text(0, 1.25, '1.25')])

### Fe+3

In [389]:
I=[1/2,0]
N=[[-1/2,1/2],[0]]
E=[-5/2,-3/2,-1/2,1/2,3/2,5/2]
amp=[1-0.97881,0.97881]

g=1.987802807
A=[g*mu*20.14,0]

In [391]:

x=np.linspace(3409,3443,5000)
espectro_fe=np.zeros(5000)
y=[]

absorciones=[]
uno=[]
dos=[]

for i in range(len(I)):
    for k in range(len(E)):
        for j in range(len(N[i])):
            if(k!=len(E)-1):
                B1=1/(2*g) * ((h*nu/mu - A[i]*N[i][j]/mu) + ((A[i]*N[i][j]/mu - h*nu/mu)**2 - 2*A[i]**2/(mu**2) * (I[i]*(I[i]+1)+N[i][j]*(-N[i][j]+2*E[k]+1)))**(1/2))
                uno.append(B1)
                absorciones.append(B1)
                y.append(voigt(x,amp[i],B1,0.5,0.5,0.5))
            if(k!=0):    
                B2=1/(2*g) * ((h*nu/mu + A[i]*N[i][j]/mu) + ((A[i]*N[i][j]/mu + h*nu/mu)**2 - 2*A[i]**2/(mu**2) * (I[i]*(I[i]+1)+N[i][j]*(-N[i][j]+2*E[k]-1)))**(1/2))
                absorciones.append(B2)
                y.append(voigt(x,amp[i],B2,0.5,0.5,0.5))
                dos.append(B2)
            
            
            
            
for i in range(len(y)):
    espectro_fe+=y[i]
espectro_fe=espectro_fe/max(espectro_fe)
plt.xlabel('Campo magnético $B$ ($G$)', fontsize=22)
plt.ylabel('Intensidad (u.a.)', fontsize=22)
plt.xlim(3409,3443)
plt.xticks(fontsize=22)
plt.yticks(fontsize=22)
plt.plot(x,espectro_fe)

In [363]:
fig, axs = plt.subplots(1)

axs.plot(x,espectro_fe,color='black')

for i in range(len(absorciones)):
    axs.axvline(x=absorciones[i], color='gray', linestyle='--', linewidth=1)

plt.xlabel('Campo magnético $B$ ($G$)', fontsize=22)
plt.ylabel('Intensidad (u.a.)', fontsize=22)
plt.xlim(3409,3443)
plt.xticks(fontsize=22)
plt.yticks(fontsize=22)

(array([-1.25, -1.  , -0.75, -0.5 , -0.25,  0.  ,  0.25,  0.5 ,  0.75,
         1.  ,  1.25]),
 [Text(0, -1.25, '−1.25'),
  Text(0, -1.0, '−1.00'),
  Text(0, -0.75, '−0.75'),
  Text(0, -0.5, '−0.50'),
  Text(0, -0.25, '−0.25'),
  Text(0, 0.0, '0.00'),
  Text(0, 0.25, '0.25'),
  Text(0, 0.5, '0.50'),
  Text(0, 0.75, '0.75'),
  Text(0, 1.0, '1.00'),
  Text(0, 1.25, '1.25')])

### Mn+2

In [393]:
I=[5/2]
N=[-5/2,-3/2,-1/2,1/2,3/2,5/2]
E=[-5/2,-3/2,-1/2,1/2,3/2,5/2]
amp=[1]
#amp=amp*100
g=1.987802807
A=[g*mu*114.6]

In [394]:

x=np.linspace(3050,3750,50000)
espectro_mn=np.zeros(50000)
y=[]

absorciones=[]


for i in range(len(I)):
    for k in range(len(E)):
        for j in range(len(N)):

            if (k!=len(E)-1):
                B1=1/(2*g) * ((h*nu/mu - A[i]*N[j]/mu) + ((A[i]*N[j]/mu - h*nu/mu)**2 - 2*A[i]**2/(mu**2) * (I[i]*(I[i]+1)+N[j]*(-N[j]+2*E[k]+1)))**(1/2))
                y.append(voigt(x,amp[i],B1,0.5,0.5,0.5))
                absorciones.append(B1)
            if (k!=0):
                B2=1/(2*g) * ((h*nu/mu + A[i]*N[j]/mu) + ((A[i]*N[j]/mu + h*nu/mu)**2 - 2*A[i]**2/(mu**2) * (I[i]*(I[i]+1)+N[j]*(-N[j]+2*E[k]-1)))**(1/2))
                y.append(voigt(x,amp[i],B2,0.5,0.5,0.5))
                absorciones.append(B2)
            
            
            
for i in range(len(y)):
    espectro_mn+=y[i]

espectro_mn=espectro_mn/max(espectro_mn)

plt.xlabel('Campo magnético $B$ ($G$)', fontsize=22)
plt.ylabel('Intensidad (u.a.)', fontsize=22)
plt.xlim(3050,3750)
plt.xticks(fontsize=22)
plt.yticks(fontsize=22)
plt.plot(x,espectro_mn)

In [395]:
fig, axs = plt.subplots(1)

axs.plot(x,espectro_mn, color='black')

for i in range(len(absorciones)):
    axs.axvline(x=absorciones[i], color='gray', linestyle='--', linewidth=1)

plt.xlabel('Campo magnético $B$ ($G$)', fontsize=22)
plt.ylabel('Intensidad (u.a.)', fontsize=22)
plt.xlim(3050,3750)
plt.xticks(fontsize=22)
plt.yticks(fontsize=22)

(array([-1.25, -1.  , -0.75, -0.5 , -0.25,  0.  ,  0.25,  0.5 ,  0.75,
         1.  ,  1.25]),
 [Text(0, -1.25, '−1.25'),
  Text(0, -1.0, '−1.00'),
  Text(0, -0.75, '−0.75'),
  Text(0, -0.5, '−0.50'),
  Text(0, -0.25, '−0.25'),
  Text(0, 0.0, '0.00'),
  Text(0, 0.25, '0.25'),
  Text(0, 0.5, '0.50'),
  Text(0, 0.75, '0.75'),
  Text(0, 1.0, '1.00'),
  Text(0, 1.25, '1.25')])

### Co+3

In [396]:
I=[7/2]
N=[-7/2,-5/2,-3/2,-1/2,1/2,3/2,5/2,7/2]
E=[-4,-3,-2,-1,0,1,2,3,4]
amp=[1]

g=1.236545592
A=[g*mu*172.9]

In [397]:

x=np.linspace(4700,6300,50000)
espectro_co=np.zeros(50000)
y=[]

absorciones=[]


for i in range(len(I)):
    for k in range(len(E)):
        for j in range(len(N)):
            if (k!=len(E)-1):
                B1=1/(2*g) * ((h*nu/mu - A[i]*N[j]/mu) + ((A[i]*N[j]/mu - h*nu/mu)**2 - 2*A[i]**2/(mu**2) * (I[i]*(I[i]+1)+N[j]*(-N[j]+2*E[k]+1)))**(1/2))
                y.append(voigt(x,amp[i],B1,0.5,0.5,0.5))
                absorciones.append(B1)
            if (k!=0):
                B2=1/(2*g) * ((h*nu/mu + A[i]*N[j]/mu) + ((A[i]*N[j]/mu + h*nu/mu)**2 - 2*A[i]**2/(mu**2) * (I[i]*(I[i]+1)+N[j]*(-N[j]+2*E[k]-1)))**(1/2))
                y.append(voigt(x,amp[i],B2,0.5,0.5,0.5))
                absorciones.append(B2)
            
            
            
for i in range(len(y)):
    espectro_co+=y[i]

espectro_co=espectro_co/max(espectro_co)

plt.xlabel('Campo magnético $B$ ($G$)', fontsize=22)
plt.ylabel('Intensidad (u.a.)', fontsize=22)
plt.xlim(4700,6300)
plt.xticks(fontsize=22)
plt.yticks(fontsize=22)
plt.plot(x,espectro_co)

In [398]:
fig, axs = plt.subplots(1)

axs.plot(x,espectro_co, color='black')


for i in range(len(absorciones)):
    axs.axvline(x=absorciones[i], color='gray', linestyle='--', linewidth=1)

plt.xlabel('Campo magnético $B$ ($G$)', fontsize=22)
plt.ylabel('Intensidad (u.a.)', fontsize=22)
plt.xlim(4760,6200)
plt.xticks(fontsize=22)
plt.yticks(fontsize=22)

(array([-1.25, -1.  , -0.75, -0.5 , -0.25,  0.  ,  0.25,  0.5 ,  0.75,
         1.  ,  1.25]),
 [Text(0, -1.25, '−1.25'),
  Text(0, -1.0, '−1.00'),
  Text(0, -0.75, '−0.75'),
  Text(0, -0.5, '−0.50'),
  Text(0, -0.25, '−0.25'),
  Text(0, 0.0, '0.00'),
  Text(0, 0.25, '0.25'),
  Text(0, 0.5, '0.50'),
  Text(0, 0.75, '0.75'),
  Text(0, 1.0, '1.00'),
  Text(0, 1.25, '1.25')])

# V+3

In [255]:
I=[7/2]
N=[-7/2,-5/2,-3/2,-1/2,1/2,3/2,5/2,7/2]
E=[-2,-1,0,1,2]
amp=[1]

g=1.987802807
A=[g*mu*92.11]

In [256]:

x=np.linspace(2530,4200,500000)
espectro_v=np.zeros(500000)
y=[]

absorciones=[]


for i in range(len(I)):
    for k in range(len(E)):
        for j in range(len(N)):

            B1=1/(2*g) * ((h*nu/mu - A[i]*N[j]/mu) + ((A[i]*N[j]/mu - h*nu/mu)**2 - 2*A[i]**2/(mu**2) * (I[i]*(I[i]+1)+N[j]*(-N[j]+2*E[k]+1)))**(1/2))
            B2=1/(2*g) * ((h*nu/mu + A[i]*N[j]/mu) + ((A[i]*N[j]/mu + h*nu/mu)**2 - 2*A[i]**2/(mu**2) * (I[i]*(I[i]+1)+N[j]*(-N[j]+2*E[k]-1)))**(1/2))

            y.append(voigt(x,amp[i],B1,0.5,0.5,0.5))
            y.append(voigt(x,amp[i],B2,0.5,0.5,0.5))
            absorciones.append(B1)
            absorciones.append(B2)
for i in range(len(y)):
    espectro_v+=y[i]

espectro_v=espectro_v/max(espectro_v[:])
plt.xlabel('Campo magnético $B$ ($G$)', fontsize=14)
plt.ylabel('Intensidad (u.a.)', fontsize=14)
plt.xlim()

plt.xticks(fontsize=14)
plt.yticks(fontsize=14)
plt.plot(x,espectro_v)

In [257]:
fig, axs = plt.subplots(1)

axs.plot(x,espectro_v)


for i in range(len(absorciones)):
    axs.axvline(x=absorciones[i], color='red', linestyle='--', linewidth=1)
plt.xlabel('Campo magnético $B$ ($G$)', fontsize=14)
plt.ylabel('Intensidad (u.a.)', fontsize=14)
plt.xlim(2530,4200)
plt.xticks(fontsize=14)
plt.yticks(fontsize=14)

(array([-1.25, -1.  , -0.75, -0.5 , -0.25,  0.  ,  0.25,  0.5 ,  0.75,
         1.  ,  1.25]),
 [Text(0, -1.25, '−1.25'),
  Text(0, -1.0, '−1.00'),
  Text(0, -0.75, '−0.75'),
  Text(0, -0.5, '−0.50'),
  Text(0, -0.25, '−0.25'),
  Text(0, 0.0, '0.00'),
  Text(0, 0.25, '0.25'),
  Text(0, 0.5, '0.50'),
  Text(0, 0.75, '0.75'),
  Text(0, 1.0, '1.00'),
  Text(0, 1.25, '1.25')])